FROM node:21-alpine
RUN wget -qO /bin/pnpm "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" && chmod +x /bin/pnpm

WORKDIR /usr/src/app/
ENV NODE_ENV=development
EXPOSE 3001

# By doing this separate we allow Docker to cache this
COPY package.json pnpm-lock.yaml /usr/src/app/
RUN pnpm install

COPY ./src/ /usr/src/app/src/
COPY ./migrations/ /usr/src/app/migrations/
COPY ./scripts/ /usr/src/app/scripts/

CMD pnpm run migrate && pnpm run start
