FROM node:11.11-alpine

WORKDIR /usr/src/app/
ENV NODE_ENV=development
EXPOSE 3001

# By doing this separate we allow Docker to cache this
COPY package.json package-lock.json /usr/src/app/
RUN npm install

COPY . /usr/src/app/

CMD npm run migrate && ./node_modules/.bin/nodemon --legacy-watch --exec babel-node src/index.js
